import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { SignUpButton } from "@clerk/nextjs";
import Image from "next/image";
import { FaGithub } from "react-icons/fa";

const images = [
  "/dragon.png",
  "/cat.png",
  "/doggy.png",
  "/magician.png",
  "/zombie.png",
  "/brown_bear.png",
  "/eagle.png",
  "/cyborg.png",
];
export default function LandingPage() {
  return (
    <div className="min-h-screen flex flex-col">
      {/* Hero Section */}
      <section className="h-[80vh] relative flex-grow flex items-center justify-center bg-gradient-to-b from-background to-secondary overflow-hidden">
        <div className="absolute inset-0 z-0">
          <div className="grid grid-cols-3 md:grid-cols-4 gap-4 p-4">
            {[...Array(12)].map((_, i) => (
              <div
                key={i}
                className="aspect-square relative overflow-hidden rounded-lg"
              >
                <Image
                  src={images[i % images.length]}
                  alt={`Image ${i + 1}`}
                  width={300}
                  height={300}
                  className="object-cover transition-transform duration-300 hover:scale-110"
                />
              </div>
            ))}
          </div>
        </div>
        <div className="relative z-10 text-center space-y-6 p-8 bg-background/80 backdrop-blur-sm rounded-lg shadow-lg">
          <h1 className="text-4xl md:text-6xl font-bold text-primary">
            Welcome to GenWalls
          </h1>
          <p className="text-xl md:text-2xl text-muted-foreground max-w-2xl mx-auto">
            Create, share, and enjoy <br /> the best images generated by the
            community
          </p>
          <Button
            asChild
            size="lg"
            className="bg-primary text-primary-foreground hover:bg-blue-700"
          >
            <SignUpButton>Join the community</SignUpButton>
          </Button>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-16 bg-card">
        <div className="container mx-auto px-4">
          <h2 className="text-3xl font-bold text-center mb-12 text-primary">
            Why Choose GenWalls?
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            <FeatureCard
              title="Easy Image Creation"
              description="Create stunning images in seconds with our intuitive image generator."
            />
            <FeatureCard
              title="Quality Images"
              description="Access thousands of high-quality images generated by the community."
            />
            <FeatureCard
              title="Vibrant Community"
              description="Share your images and interact with fellow image enthusiasts."
            />
          </div>
        </div>
      </section>

      {/* Footer Section */}
      <footer className="py-4 bg-background text-center">
        <p className="text-sm text-muted-foreground">
          Created by Salif Tankoano
        </p>
        <div className="flex justify-center space-x-4 mt-2">
          <a
            href="https://saliftankoano.com"
            className="text-primary hover:underline"
          >
            My Website
          </a>
          <a
            href="https://www.linkedin.com/in/salif-tankoano/"
            className="text-primary hover:underline"
          >
            LinkedIn
          </a>
          <a
            href="https://github.com/saliftankoano"
            className="text-primary hover:underline"
          >
            <FaGithub size={24} />
          </a>
        </div>
      </footer>
    </div>
  );
}

function FeatureCard({
  title,
  description,
}: {
  title: string;
  description: string;
}) {
  return (
    <Card className="text-center">
      <CardHeader>
        <CardTitle>{title}</CardTitle>
      </CardHeader>
      <CardContent>
        <p>{description}</p>
      </CardContent>
    </Card>
  );
}
